apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ipmi-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipmi-exporter
      type: exporter
  template:
    metadata:
      labels:
        app: ipmi-exporter
        type: exporter
    spec:
      containers:
      - name: ipmi-exporter
        image: "ipmi-exporter:v0.0.3"
        env:
        - name: APP_ENV
          value: "dev"
        - name: IPMI_USER
          value: ""
        - name: IPMI_PASSWORD
          value: ""
        ports:
        - containerPort: 9290
